#!/bin/bash

function run_nebula() {
echo Building tables on target=$2, split_key=$4, and region=$3
sbatch --ntasks-per-node=1 --cpus-per-task=1 --mem=500G -t 24:00:00 --qos=normal -p celltypes -J "${2/\// }"_$4_$3 -o "SLURM/slurm-%j.out" --mail-type=FAIL <<END
#!/bin/bash

source ~/.bashrc
conda activate sc
python run_nebula.py --threads "$1" --target "$2" --region "$3" --split_key "$4" --random_effect "$5" --covariates "$6" --covariate_formula "$7" --tests "$8" --layer "$9" --offset_variable "$10"
exit 0

END
}

# Primary test across CPS
run_nebula 32 "Astrocyte" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Microglia-PVM" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "OPC" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Endothelial" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "VLMC" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Oligodendrocyte" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 3 "L2/3 IT" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L4 IT" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 IT" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT Car3" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 ET" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5/6 NP" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 CT" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6b" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pvalb" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Chandelier" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst Chodl" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Vip" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sncg" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5 Lhx6" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pax6" MTG Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs

# Secondary differential expression test in each epoch
run_nebula 32 "Astrocyte" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Microglia-PVM" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "OPC" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Endothelial" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "VLMC" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Oligodendrocyte" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 3 "L2/3 IT" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L4 IT" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 IT" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT Car3" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 ET" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5/6 NP" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 CT" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6b" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pvalb" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Chandelier" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst Chodl" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Vip" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sncg" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5 Lhx6" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pax6" MTG_early Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs

run_nebula 32 "Astrocyte" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Microglia-PVM" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "OPC" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Endothelial" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "VLMC" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Oligodendrocyte" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 3 "L2/3 IT" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L4 IT" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 IT" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 IT Car3" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5 ET" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L5/6 NP" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6 CT" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "L6b" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pvalb" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Chandelier" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sst Chodl" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Vip" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Sncg" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Lamp5 Lhx6" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs
run_nebula 32 "Pax6" MTG_late Supertype Donor_ID Age_at_Death_binned_codes,Sex,Genes_detected,Race_choice_White,method "Age_at_Death_binned_codes + Sex + Genes_detected + Race_choice_White + method + " Continuous_Pseudo-progression_Score X Number_of_UMIs

